// <auto-generated />
using Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PersistenceContext))]
    partial class PersistenceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TblModules", "Auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vehículos"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Reservas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Historial de Reservas"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Configuraciones"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TblRoles", "Auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Asesor"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RoleModule", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("TblRolesModules", "Auth");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            ModuleId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            ModuleId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            ModuleId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            ModuleId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            ModuleId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            ModuleId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("TblUsers", "Auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "pedroperez@reservation.com",
                            EmployeeId = 1,
                            Password = new byte[] { 161, 118, 217, 111, 167, 156, 25, 14, 239, 16, 230, 181, 142, 149, 34, 213, 237, 106, 251, 70, 232, 110, 102, 66, 4, 203, 69, 192, 83, 159, 45, 213, 29, 92, 189, 8, 67, 61, 20, 175, 172, 70, 70, 35, 38, 247, 196, 33, 203, 208, 122, 98, 183, 231, 253, 108, 100, 149, 195, 157, 215, 19, 182, 143 },
                            PasswordKey = new byte[] { 7, 90, 116, 245, 64, 154, 217, 179, 9, 218, 99, 68, 95, 58, 43, 27, 98, 230, 19, 130, 122, 0, 125, 154, 209, 126, 87, 252, 60, 200, 67, 219, 177, 229, 158, 40, 25, 36, 223, 154, 79, 81, 135, 243, 60, 207, 71, 102, 96, 78, 192, 255, 122, 178, 184, 68, 52, 136, 48, 87, 68, 57, 4, 205, 231, 158, 131, 1, 136, 149, 238, 70, 132, 97, 42, 231, 89, 96, 67, 137, 80, 239, 7, 205, 201, 111, 150, 130, 95, 12, 172, 239, 163, 50, 234, 99, 97, 97, 69, 166, 218, 203, 155, 133, 184, 118, 183, 164, 42, 218, 101, 127, 201, 233, 96, 203, 60, 5, 118, 75, 226, 120, 75, 57, 118, 114, 131, 10 },
                            RoleId = 1,
                            Username = "pedroperez"
                        },
                        new
                        {
                            Id = 2,
                            Email = "grabrielgomez@bookingcar.com",
                            EmployeeId = 2,
                            Password = new byte[] { 186, 29, 179, 108, 173, 93, 137, 117, 80, 79, 230, 163, 57, 71, 144, 221, 24, 153, 47, 84, 9, 177, 236, 118, 82, 61, 32, 97, 124, 99, 24, 243, 232, 126, 12, 163, 217, 242, 139, 77, 213, 113, 58, 151, 80, 247, 185, 200, 214, 88, 54, 3, 138, 108, 114, 19, 198, 52, 80, 211, 165, 51, 223, 170 },
                            PasswordKey = new byte[] { 70, 112, 6, 203, 47, 38, 19, 198, 226, 122, 44, 13, 18, 85, 101, 245, 173, 53, 184, 104, 204, 148, 86, 192, 132, 76, 240, 104, 48, 144, 176, 11, 169, 47, 184, 77, 2, 167, 209, 33, 223, 64, 38, 150, 200, 197, 172, 193, 180, 135, 236, 185, 123, 162, 161, 81, 184, 247, 105, 123, 51, 12, 47, 225, 74, 28, 28, 183, 135, 199, 251, 47, 95, 153, 96, 204, 78, 243, 165, 114, 209, 200, 103, 44, 89, 193, 209, 226, 22, 228, 61, 20, 14, 185, 155, 75, 17, 151, 219, 18, 53, 64, 34, 119, 248, 34, 152, 41, 150, 81, 51, 127, 163, 199, 211, 113, 51, 17, 40, 53, 235, 193, 247, 188, 66, 109, 68, 118 },
                            RoleId = 2,
                            Username = "grabrielgomez"
                        },
                        new
                        {
                            Id = 3,
                            Email = "rodolforuiz@bookingcar.com",
                            EmployeeId = 3,
                            Password = new byte[] { 12, 34, 72, 77, 214, 100, 88, 65, 240, 13, 220, 221, 88, 96, 15, 163, 201, 97, 185, 79, 32, 254, 238, 17, 121, 28, 234, 237, 110, 244, 107, 252, 181, 158, 240, 176, 103, 95, 32, 108, 206, 88, 123, 38, 83, 131, 223, 163, 226, 232, 45, 32, 199, 87, 80, 233, 128, 133, 11, 154, 51, 45, 45, 102 },
                            PasswordKey = new byte[] { 176, 99, 116, 190, 219, 136, 250, 242, 233, 0, 133, 65, 130, 206, 33, 166, 179, 227, 210, 115, 254, 16, 196, 90, 238, 234, 43, 223, 39, 72, 253, 173, 128, 255, 76, 237, 124, 233, 111, 12, 61, 145, 100, 129, 238, 2, 82, 167, 130, 181, 87, 108, 244, 77, 203, 253, 178, 200, 108, 183, 6, 10, 103, 96, 240, 235, 187, 20, 49, 91, 212, 18, 17, 145, 240, 5, 96, 11, 5, 75, 187, 130, 141, 122, 46, 186, 62, 45, 40, 6, 243, 136, 58, 201, 11, 37, 206, 190, 151, 102, 244, 91, 150, 23, 23, 159, 5, 161, 234, 27, 234, 23, 2, 87, 160, 93, 232, 0, 218, 184, 123, 36, 70, 224, 171, 147, 54, 30 },
                            RoleId = 2,
                            Username = "rodolforuiz"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RoleModule", b =>
                {
                    b.HasOne("Domain.Entities.Module", "Module")
                        .WithMany("RoleModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("RoleModules")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Module", b =>
                {
                    b.Navigation("RoleModules");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("RoleModules");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
